baseURL = "https://ramonmacias.github.io/"
languageCode = "en-us"
title = "Blog Not Found"
theme = "hugo-theme-cleanwhite"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true

[params]
  header_image = "img/tavascan_winter.jpg"
  SEOTitle = "Ramon Blog"
  description = "The Ramon personal blog"
  keyword = "Ramon, Macias, Blog, Go, Computer"
  slogan = "Be nil my friend"

  image_404 = "img/404-bg.jpg"
  title_404 = "Sorry we can't find your page :("
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  sidebar_avatar = "img/zhaohuabing.png"

  featured_tags = false
  featured_condition_size = 1

  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss = true
  email = "ramonmaciasgarcia@gmail.com"
  linkedin = "https://www.linkedin.com/in/ramon-macias-garcia-4a407365/"
  github = "https://github.com/ramonmacias"

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"
